# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Luis Guerrero
tagline:          'Building great products one at a time'
description:      'Product Manager with 10+ years of experience in software development. Entrepreneur.'
url:              http://joseluishdz.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5
plugins:          [jekyll-paginate]

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
