# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            José Luis Hernández
tagline:          'Developer World'
description:      'You think development is your ally, but you merely adopted the code. I was born in it, molded by it. Until I was already a man, it was nothing to me but coding.'
url:              http://joseluishernandez.me
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
